services:
  led-matrix:
    build: ./led-matrix
    container_name: led-matrix
    restart: unless-stopped
    privileged: true
    volumes:
      - ./state.json:/app/state.json
      - ./.env:/app/.env
    environment:
      GPIOZERO_PIN_FACTORY: pigpio
      PIGPIO_ADDR: pigpiod
      PIGPIO_PORT: 8888
      TZ: America/Edmonton
    depends_on:
      - pigpiod
    profiles:
      - led-matrix

  pir-ctrl:
    build: ./pir-ctrl
    container_name: pir-ctrl
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GPIOZERO_PIN_FACTORY: pigpio
      PIGPIO_ADDR: pigpiod
      PIGPIO_PORT: 8888
    depends_on:
      - pigpiod

  pigpiod:
    image: zinen2/alpine-pigpiod:latest
    container_name: pigpiod
    restart: unless-stopped
    privileged: true
